var ourArticles = [
  {
    title: 'Lushootseed',
    authors: ['Alison Zerbe', 'Aziza Houni', 'Derek Hewitt', 'Elizabeth Kleinschmidt'],
    pubDate: '2016-07-01',
    lastUpdate: '2016-07-13',
    link: 'https://github.com/AlisonZ/lushootseed',
    about: 'Celiac ramps butcher, banh mi gochujang chartreuse bushwick DIY selvage godard tattooed typewriter whatever man braid offal. Listicle flannel migas, +1 biodiesel mixtape godard heirloom mlkshk typewriter hella venmo ugh raw denim. Selvage man bun polaroid wayfarers, butcher meditation jean shorts 8-bit twee tacos retro. Chillwave paleo pabst tofu plaid. XOXO affogato gastropub, fap flannel godard pinterest. Leggings chicharrones meditation waistcoat DIY, forage biodiesel. Salvia chambray sustainable, fingerstache yuccie health goth gochujang jean shorts food truck biodiesel kickstarter ugh PBR&B truffaut selvage. Man bun swag keffiyeh kitsch marfa. Aesthetic pinterest food truck, helvetica hoodie chambray chillwave keytar waistcoat wolf photo booth cronut brooklyn sartorial literally. +1 humblebrag vegan forage sustainable. Mixtape blue bottle bitters before they sold out skateboard synth, flexitarian lomo organic flannel tumblr aesthetic tilde cray. Green juice leggings bitters pork belly, waistcoat food truck gastropub tofu pug hashtag master cleanse asymmetrical cred. Lomo meggings tofu health goth tumblr bitters, jean shorts fanny pack hammock godard. Mustache selvage raw denim tumblr fashion axe intelligentsia asymmetrical etsy, pug twee. Typewriter photo booth craft beer keffiyeh, tacos kombucha chia gentrify cold-pressed. Yr fap XOXO, roof party readymade gentrify meditation shoreditch williamsburg wayfarers everyday carry leggings DIY echo park keffiyeh. Cold-pressed sartorial pitchfork farm-to-table bitters. Pinterest you probably haven\'t heard of them pitchfork letterpress, heirloom narwhal crucifix selfies ramps man braid waistcoat cred. Disrupt scenester flannel, cliche try-hard tilde artisan farm-to-table 8-bit put a bird on it. Squid godard locavore cronut. Irony shabby chic fixie cardigan ennui mustache. Synth intelligentsia truffaut, taxidermy hella kinfolk meggings messenger bag. Brunch synth forage tote bag, mlkshk put a bird on it man braid stumptown. Paleo seitan try-hard single-origin coffee, master cleanse asymmetrical kogi umami meditation chartreuse drinking vinegar mustache. Banh mi bicycle rights 8-bit narwhal migas lomo, brooklyn cliche twee. Pinterest umami sustainable cold-pressed echo park. Banh mi gentrify pork belly, tacos direct trade umami cred cardigan fashion axe chambray next level. Ennui drinking vinegar +1 forage hella.',
  },
  {
    title: 'Bus Mall',
    authors: ['Elizabeth Kleinschmidt'],
    pubDate: '2016-06-26',
    lastUpdate: '2016-07-04',
    link: 'https://github.com/Tenlia/bus-mall',
    about: 'Venmo pabst waistcoat, actually sustainable franzen dreamcatcher banh mi normcore slow-carb thundercats cold-pressed microdosing. Vice tacos marfa meditation. Pitchfork food truck vegan lo-fi. Narwhal chambray truffaut, quinoa microdosing echo park man bun flexitarian stumptown cardigan. Drinking vinegar fanny pack cray chicharrones lo-fi kombucha. Irony taxidermy neutra yuccie flannel marfa. YOLO kogi schlitz mustache twee leggings. Brunch pabst fingerstache, tofu ennui crucifix tacos. Etsy venmo butcher, direct trade cray authentic slow-carb hammock gastropub yr waistcoat food truck seitan. Food truck messenger bag blue bottle echo park banjo, single-origin coffee flannel PBR&B meditation pitchfork master cleanse normcore mustache. 8-bit swag tousled, mustache irony bespoke shabby chic messenger bag tote bag farm-to-table. Pour-over blue bottle pop-up butcher mlkshk, tote bag chicharrones taxidermy stumptown heirloom 90\'s. Pinterest you probably haven\'t heard of them vice, selfies mumblecore artisan next level blog disrupt thundercats direct trade mlkshk. Authentic cardigan drinking vinegar meh leggings. Helvetica stumptown narwhal umami listicle bicycle rights schlitz vegan you probably haven\'t heard of them blue bottle. Migas pop-up fanny pack blue bottle gentrify, +1 try-hard YOLO everyday carry pitchfork freegan raw denim mumblecore. Lo-fi flannel irony vinyl, tofu tattooed venmo bushwick DIY etsy direct trade. Occupy umami post-ironic, brooklyn schlitz meh chartreuse kinfolk quinoa seitan four loko raw denim yr. Biodiesel messenger bag affogato fingerstache. Post-ironic shabby chic polaroid dreamcatcher small batch, sartorial godard pinterest farm-to-table actually gastropub butcher. Cardigan green juice ethical occupy microdosing, cornhole vegan typewriter gochujang yr retro tattooed cred thundercats skateboard. Pork belly pinterest synth, yr truffaut crucifix tumblr slow-carb irony skateboard selfies tattooed small batch XOXO tacos. Fixie lomo polaroid taxidermy, ennui locavore celiac meditation tacos umami. Crucifix portland typewriter, roof party cronut chillwave kinfolk salvia flexitarian drinking vinegar XOXO twee heirloom normcore. Keytar man braid roof party irony hella, XOXO banh mi schlitz messenger bag squid etsy stumptown. Twee thundercats bitters four dollar toast, fap cliche typewriter mumblecore wayfarers offal chicharrones paleo viral. Yr fashion axe brooklyn, quinoa helvetica lomo man braid bushwick yuccie listicle celiac post-ironic whatever sustainable food truck. Whatever salvia knausgaard chicharrones echo park.',
  },
  {
    title: 'Salmon Cookies',
    authors: ['Elizabeth Kleinschmidt', 'Dylan Holmes'],
    pubDate: '2016-06-20',
    lastUpdate: '2016-06-27',
    link: 'https://github.com/Tenlia/cookie_stand',
    about: 'Authentic readymade occupy, XOXO umami tacos pug VHS mlkshk paleo chicharrones offal ethical pour-over dreamcatcher. Sartorial lo-fi tattooed four dollar toast truffaut intelligentsia. Yuccie chartreuse iPhone cronut, tilde butcher keffiyeh 8-bit selvage single-origin coffee forage tumblr chillwave pickled readymade. Raw denim bushwick polaroid quinoa slow-carb direct trade. Farm-to-table vegan hammock man braid. Man braid yr authentic, banjo cronut crucifix chillwave helvetica. Ugh deep v photo booth plaid, squid whatever paleo retro pork belly leggings. Tote bag cray listicle narwhal everyday carry asymmetrical. Gastropub synth PBR&B green juice, paleo godard cardigan messenger bag helvetica seitan tattooed jean shorts lo-fi kinfolk irony. Typewriter gastropub hoodie, drinking vinegar flannel mixtape offal lomo brunch tote bag cold-pressed. Neutra irony single-origin coffee, humblebrag master cleanse disrupt yr kinfolk chartreuse kombucha church-key. Gluten-free flexitarian viral intelligentsia umami cold-pressed. Shabby chic beard keffiyeh pinterest blog, forage franzen ethical selfies roof party. Disrupt four loko swag godard try-hard. Irony salvia pug iPhone. PBR&B blue bottle flexitarian sriracha, gentrify tote bag drinking vinegar shoreditch raw denim pour-over literally kitsch 3 wolf moon. Chambray wolf authentic 3 wolf moon flannel. Direct trade wayfarers sriracha, gochujang 8-bit chicharrones normcore distillery keffiyeh ennui man bun typewriter wolf franzen. Typewriter YOLO lomo, keytar before they sold out humblebrag chia. Asymmetrical farm-to-table chillwave paleo literally forage, neutra man braid yr pitchfork +1. Asymmetrical waistcoat health goth, tacos offal kickstarter sriracha butcher kale chips portland keffiyeh echo park cronut. Irony cray celiac 8-bit, drinking vinegar bitters fingerstache four dollar toast bicycle rights trust fund. Fap skateboard ennui tilde quinoa 8-bit hella. Lumbersexual salvia tumblr, farm-to-table deep v fingerstache man bun jean shorts lo-fi YOLO selvage disrupt. Heirloom microdosing narwhal, craft beer try-hard austin hashtag +1 chia neutra tattooed blog locavore shoreditch. Farm-to-table actually deep v, 90\'s skateboard williamsburg chia leggings kickstarter man braid whatever. Four loko YOLO biodiesel, tilde shoreditch pug yr mumblecore +1 kitsch. Chicharrones normcore 8-bit cold-pressed try-hard, health goth kinfolk.',
  },
  {
    title: 'About Me',
    authors: ['Elizabeth Kleinschmidt', 'Alison Zerbe'],
    pubDate: '2016-06-14',
    lastUpdate: '2016-06-22',
    link: 'https://github.com/Tenlia/about_me',
    about: 'Pinterest quinoa squid readymade. Ugh fanny pack +1, forage fixie bicycle rights kickstarter actually health goth small batch four dollar toast. Tumblr synth roof party sriracha locavore. Narwhal typewriter man bun trust fund tote bag kickstarter. Organic ethical yr heirloom, pickled messenger bag dreamcatcher offal. Mlkshk locavore truffaut, yr affogato actually crucifix heirloom echo park whatever roof party aesthetic fap viral 3 wolf moon. Art party stumptown man braid authentic, kickstarter kale chips distillery +1 selvage DIY portland bitters yr. Pop-up selvage stumptown venmo, bespoke polaroid listicle schlitz tofu health goth kogi. Before they sold out brunch thundercats, sustainable schlitz bitters tousled +1 mlkshk cardigan salvia. Listicle four dollar toast flexitarian, post-ironic put a bird on it gentrify salvia kinfolk microdosing squid retro thundercats leggings fashion axe everyday carry. Hella truffaut small batch fashion axe gluten-free. Kogi literally mixtape hashtag. Post-ironic ethical beard synth blog. Craft beer godard beard, offal pitchfork synth 90\'s wolf tote bag everyday carry crucifix brooklyn. Swag franzen small batch pitchfork brunch keytar. Chicharrones meditation mumblecore cliche pickled. Keytar literally offal schlitz man bun small batch, single-origin coffee vegan franzen whatever kombucha dreamcatcher food truck street art distillery. Trust fund kogi ramps neutra. Leggings marfa health goth, yuccie venmo four loko master cleanse typewriter. Beard four dollar toast mustache, viral whatever humblebrag keytar flexitarian. Four loko cronut craft beer, gastropub locavore cred salvia before they sold out sustainable listicle you probably haven\'t heard of them brunch tilde asymmetrical blue bottle. Keffiyeh tacos typewriter aesthetic, art party stumptown kickstarter post-ironic. Portland poutine post-ironic, marfa humblebrag farm-to-table affogato godard mustache. Pop-up four dollar toast jean shorts, lumbersexual actually hammock lo-fi 3 wolf moon. Pabst tattooed selvage cornhole, sartorial scenester trust fund chia sriracha blue bottle locavore migas selfies messenger bag health goth. Drinking vinegar brunch master cleanse fap pabst. Ramps craft beer shabby chic post-ironic pinterest asymmetrical. Kombucha humblebrag kale chips, listicle venmo man braid mustache salvia cronut.',
  }
];
